server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        clientID: resource_server
        secret: resource_server_secret
        jwt:
          issuer-uri: http://127.0.0.1:9000
          keySetURI: http://127.0.0.1:9000/oauth2/jwks
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
keySetURI: http://localhost:9090/oauth2/jwks
introspectionUri: http://127.0.0.1:9000/oauth2/introspect

