server:
  port: 8080
  servlet:
    session:
      cookie:
        samesite: None
        secure: false
        http-only: true
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          keySetURI: http://localhost:9000/oauth2/jwks
keySetURI: http://localhost:9090/oauth2/jwks