create table if not exists User_data (
    id bigint generated by default as identity,
    email varchar(100) not null,
    password varchar(100) not null,
    firstName varchar(25) not null,
    lastName varchar(25) not null,
    phone varchar(9) not null,
    userCity varchar(20),
    userStreet varchar(50),
    userZip varchar(6)
);

create table if not exists Offer_data (
    id bigint generated by default as identity primary key,
    userId bigint not null,
    creationDate timestamp,
    offerName varchar(60) not null,
    city varchar(20) not null,
    district varchar(20) not null,
    street varchar(30) not null,
    zip varchar(6),
    buildingYear smallint,
    fullPrice double not null,
    basePrice double,
    additionalPrice double,
    area int not null,
    roomsNumber smallint not null,
    garage bool,
    annexKitchen bool,
    elevator bool,
    animals bool,
    estateLevel smallint
);

create table if not exists offer_images (
    offer_id bigint not null,                -- Foreign key to Offer_data table
    image_id bigint not null,                -- Image ID
    primary key (offer_id, image_id),        -- Composite primary key to avoid duplicates
    foreign key (offer_id) references Offer_data(id) on delete cascade
);